clone_depth: 50

platform:
    - x64

configuration:
    # - Debug
    # - Release
    - RelWithDebInfo

install:
    - git submodule update --init --recursive
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S mingw-w64-x86_64-cmake
    - pacman --noconfirm -S mingw-w64-x86_64-extra-cmake-modules
    - pacman --noconfirm -S mingw-w64-x86_64-jemalloc
    - pacman --noconfirm -S mingw-w64-x86_64-boost
    - pacman --noconfirm -S mingw-w64-x86_64-libxml++2.6
    - pacman --noconfirm -S mingw-w64-x86_64-jasper
    - pacman --noconfirm -S mingw-w64-x86_64-qt5-static
    - pacman --noconfirm -S mingw-w64-x86_64-qwt-qt5

before_build:
    - md install
    - md build

build_script:
    - cd build
    - cmake .. -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_FLAGS="-O3" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH="C:/msys64/mingw64/qt5-static" -DBUILD_SHARED_LIBS=ON
    - make install/strip -j 2
    - cmake .. -DPACKAGE=ON
    - cpack
    - cd ..

after_build:
    - set PATH=%PATH%;%CD%\install\bin

test_script:
    - scram_tests
    - scram --version
    - scram input\TwoTrain\two_train.xml

artifacts:
    - path: build/SCRAM*.exe
      name: installer
