internal:
    - name: scram
      path: .
      packages:
          - name: include
            include:
                - .
          - name: core
            src:
                - src
            ignore:
                - src/tags
                - src/ext
          - name: gui
            src:
                - gui
            ignore:
                - gui/tests
                - gui/main.cpp
          - name: ext
            src:
                - src/ext
external:
    - name: Dependencies
      path: /usr/include
      packages:
          - name: STL
            pattern:
                - "[a-z_]+$"
          - name: Boost
            pattern:
                - boost
          - name: LibXML
            pattern:
                - libxml
          - name: Qt5
            pattern:
                - Q\w+
                - ui_
          - name: Windows System
            pattern:
                - windows.h
