sudo: required
dist: trusty

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

# This explicit matrix inclusion is provided
# to work around the default beta-xcode6.1 clang,
# which is having a trouble with C++11 features.
# There seems not to be a way to use 'osx_image' multiplier
# outside of this matrix
# without messing with Linux builds.
matrix:
    include:
        - os: osx
          compiler: clang
          osx_image: xcode7.3
          env: RELEASE=
        - os: osx
          compiler: clang
          osx_image: xcode7.3
          env: RELEASE=true

env:
    global:
        - PATH=$PATH:`pwd`/install/bin
    matrix:
        - RELEASE=
        - RELEASE=true

addons:
    apt:
        packages:
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-math-dev
            - libxml2-dev
            - libxml++2.6-dev
            - libgoogle-perftools-dev
            # - qt5-default
            # - graphviz

install:
    - .travis/install.sh

before_script:
    - mkdir install

script:
    - .travis/script.sh
