sudo: required
dist: trusty

language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/pip

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$PATH:`pwd`/install/bin
        - CLANG_VERSION="3.6"
        # Intel Parallel Studio
        - secure: "AY6adQXVk/3J43z6PHbqVxq3Bn5HZ5Qrf8fvPeF+BR56Oa4+9YryfDDJyiDRISuyh7PoDUw+PERJiZpAL3rkFefxUkYTB3hdU4lsMIAgl37MuT4/kP5CW9TC+gsPJl41y4i8XKFtJXF1K4PW2oDRZCbDDB9oUWPZjNPPe0jg4e8="
    matrix:
        - RELEASE=
        - RELEASE=true

matrix:
    exclude:
        - os: osx
          compiler: gcc  # GCC is Clang on OS X.
        - os: osx
          env: RELEASE=  # OS X builds are slow and limited.
    include:
        - os: linux
          compiler: icc
          env: INTEL_COMPILER=true
    allow_failures:
        - compiler: icc  # TODO: Boost problems on Travis-CI Trusty

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libglibmm-2.4-dev
            - libgoogle-perftools-dev
            - qt5-default
            - libqt5svg5-dev
            - libqt5opengl5-dev
            - qwt-qt5
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - sourceline: "ppa:kzemek/boost"
            - sourceline: "ppa:pothosware/support"

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.
    - if [[ -n "${INTEL_COMPILER}" ]]; then
          export CC=icc;
          export CXX=icpc;
          export RELEASE=true;
      fi
    - if [[ "$CXX" == "clang++" ]] && [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          export CC=clang-${CLANG_VERSION};
          export CXX=clang++-${CLANG_VERSION};
      fi

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh
