scram::mef::Initializer Class Reference
scram::mef::Initializer Class Reference
This class operates on input files to initialize analysis constructs like models, fault trees, and events.
#include <initializer.h>
Classes
struct Extractor
struct Extractor< T, 0 >
Partial specialization for terminal Extractor.
struct Extractor< T,-1 >
Specialization of Extractor to extract all expressions into arg vector.
Public Member Functions
Initializer (const std::vector< std::string > &xml_files, core::Settings settings)
Reads input files with the structure of analysis constructs.
std::shared_ptr< Model > model () const
template<>
Gate * Register (const xmlpp::Element *gate_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
BasicEvent * Register (const xmlpp::Element *event_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
HouseEvent * Register (const xmlpp::Element *event_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
Parameter * Register (const xmlpp::Element *param_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
CcfGroup * Register (const xmlpp::Element *ccf_node, const std::string &base_path, RoleSpecifier container_role)
Specializations for element registrations.
template<>
Sequence * Register (const xmlpp::Element *xml_node, const std::string &, RoleSpecifier)
Specializations for element registrations.
template<>
void Define (const xmlpp::Element *gate_node, Gate *gate)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *event_node, BasicEvent *basic_event)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *param_node, Parameter *parameter)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *ccf_node, CcfGroup *ccf_group)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *xml_node, Sequence *sequence)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *et_node, EventTree *event_tree)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *xml_node, InitiatingEvent *initiating_event)
Specializations for elements defined after registration.
template<>
void Define (const xmlpp::Element *rule_node, Rule *rule)
Specializations for elements defined after registration.
Detailed Description
This class operates on input files to initialize analysis constructs like models, fault trees, and events.
The initialization phase includes validation and proper setup of the constructs for future use or analysis.
Definition at line 57 of file initializer.h.
Constructor & Destructor Documentation
scram::mef::Initializer::Initializer (const std::vector< std::string > & xml_files, core::Settings settings)
Reads input files with the structure of analysis constructs.
Initializes the analysis model from the given input files. Puts all events into their appropriate containers in the model.
Parameters
[in] xml_files The MEF XML input files.
[in] settings Analysis settings.
Exceptions
DuplicateArgumentError Input contains duplicate files.
ValidationError The input contains errors.
IOError One of the input files is not accessible.
Definition at line 142 of file initializer.cc.
References CLOCK, scram::DEBUG1, scram::DEBUG2, DUR, scram::GetLine(), LOG, and scram::Error::msg().
Member Function Documentation
std::shared_ptr<Model> scram::mef::Initializer::model () const inline
Returns
The model built from the input files.
Definition at line 73 of file initializer.h.
References scram::mef::GetFullPath().
Referenced by Register().
The documentation for this class was generated from the following files:
initializer.h
initializer.cc